---
name: IO-Async-Loop-Glib
version: 0.16
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: 'use C<IO::Async> with F<Glib> or F<GTK>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Glib: 0
  IO::Async::Loop: 0.2
build_requires:
  Test::Exception: 0
  Test::More: 0
  Time::HiRes: 0
provides:
  IO::Async::Loop::Glib:
    file: lib/IO/Async/Loop/Glib.pm
    version: 0.16
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
