---
abstract: 'use C<IO::Async> with F<Glib> or F<GTK>'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  IO::Async::LoopTests: 0.24
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Async-Loop-Glib
provides:
  IO::Async::Loop::Glib:
    file: lib/IO/Async/Loop/Glib.pm
    version: 0.19
requires:
  Glib: 0
  IO::Async::Loop: 0.24
  Time::HiRes: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
